IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('[FK_ATAQUE-POR-APRENDER_ATAQUE]') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1) 
ALTER TABLE [ATAQUE-POR-APRENDER] DROP CONSTRAINT [FK_ATAQUE-POR-APRENDER_ATAQUE]
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('[FK_ATAQUE-POR-APRENDER_ESPECIE]') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1) 
ALTER TABLE [ATAQUE-POR-APRENDER] DROP CONSTRAINT [FK_ATAQUE-POR-APRENDER_ESPECIE]
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('[FK_BICHO_ESPECIE]') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1) 
ALTER TABLE [BICHO] DROP CONSTRAINT [FK_BICHO_ESPECIE]
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('[FK_BICHO_TIPOBICHO]') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1) 
ALTER TABLE [BICHO] DROP CONSTRAINT [FK_BICHO_TIPOBICHO]
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('[FK_BICHO-ATAQUE_ATAQUE]') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1) 
ALTER TABLE [BICHO-ATAQUE] DROP CONSTRAINT [FK_BICHO-ATAQUE_ATAQUE]
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('[FK_BICHO-ATAQUE_BICHO]') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1) 
ALTER TABLE [BICHO-ATAQUE] DROP CONSTRAINT [FK_BICHO-ATAQUE_BICHO]
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('[FK_COMBATE_USUARIO]') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1) 
ALTER TABLE [COMBATE] DROP CONSTRAINT [FK_COMBATE_USUARIO]
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('[FK_COMBATE_USUARIO_02]') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1) 
ALTER TABLE [COMBATE] DROP CONSTRAINT [FK_COMBATE_USUARIO_02]
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('[FK_ESPECIE-DEBILIDAD_ESPECIE]') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1) 
ALTER TABLE [ESPECIE-DEBILIDAD] DROP CONSTRAINT [FK_ESPECIE-DEBILIDAD_ESPECIE]
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('[FK_ESPECIE-DEBILIDAD_TIPOBICHO]') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1) 
ALTER TABLE [ESPECIE-DEBILIDAD] DROP CONSTRAINT [FK_ESPECIE-DEBILIDAD_TIPOBICHO]
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('[FK_ESPECIE-FORTALEZA_ESPECIE]') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1) 
ALTER TABLE [ESPECIE-FORTALEZA] DROP CONSTRAINT [FK_ESPECIE-FORTALEZA_ESPECIE]
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('[FK_ESPECIE-FORTALEZA_TIPOBICHO]') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1) 
ALTER TABLE [ESPECIE-FORTALEZA] DROP CONSTRAINT [FK_ESPECIE-FORTALEZA_TIPOBICHO]
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('[FK_EVOLUCION_ESPECIE]') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1) 
ALTER TABLE [EVOLUCION] DROP CONSTRAINT [FK_EVOLUCION_ESPECIE]
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('[FK_EVOLUCION_ESPECIE_02]') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1) 
ALTER TABLE [EVOLUCION] DROP CONSTRAINT [FK_EVOLUCION_ESPECIE_02]
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('[FK_INTERCAMBIO_BICHO]') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1) 
ALTER TABLE [INTERCAMBIO] DROP CONSTRAINT [FK_INTERCAMBIO_BICHO]
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('[FK_INTERCAMBIO_USUARIO]') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1) 
ALTER TABLE [INTERCAMBIO] DROP CONSTRAINT [FK_INTERCAMBIO_USUARIO]
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('[FK_INTERCAMBIO_USUARIO_02]') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1) 
ALTER TABLE [INTERCAMBIO] DROP CONSTRAINT [FK_INTERCAMBIO_USUARIO_02]
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('[FK_RONDA_COMBATE]') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1) 
ALTER TABLE [RONDA] DROP CONSTRAINT [FK_RONDA_COMBATE]
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('[FK_RONDA-ATAQUE-BICHO_ATAQUE]') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1) 
ALTER TABLE [RONDA-ATAQUE-BICHO] DROP CONSTRAINT [FK_RONDA-ATAQUE-BICHO_ATAQUE]
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('[FK_RONDA-ATAQUE-BICHO_BICHO]') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1) 
ALTER TABLE [RONDA-ATAQUE-BICHO] DROP CONSTRAINT [FK_RONDA-ATAQUE-BICHO_BICHO]
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('[FK_RONDA-ATAQUE-BICHO_RONDA]') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1) 
ALTER TABLE [RONDA-ATAQUE-BICHO] DROP CONSTRAINT [FK_RONDA-ATAQUE-BICHO_RONDA]
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('[FK_USUARIO-BICHO_BICHO]') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1) 
ALTER TABLE [USUARIO-BICHO] DROP CONSTRAINT [FK_USUARIO-BICHO_BICHO]
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('[FK_USUARIO-BICHO_USUARIO]') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1) 
ALTER TABLE [USUARIO-BICHO] DROP CONSTRAINT [FK_USUARIO-BICHO_USUARIO]
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('[FK_USUARIO-BICHO-COMBATE_BICHO]') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1) 
ALTER TABLE [USUARIO-BICHO-COMBATE] DROP CONSTRAINT [FK_USUARIO-BICHO-COMBATE_BICHO]
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('[FK_USUARIO-BICHO-COMBATE_COMBATE]') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1) 
ALTER TABLE [USUARIO-BICHO-COMBATE] DROP CONSTRAINT [FK_USUARIO-BICHO-COMBATE_COMBATE]
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('[FK_USUARIO-BICHO-COMBATE_USUARIO]') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1) 
ALTER TABLE [USUARIO-BICHO-COMBATE] DROP CONSTRAINT [FK_USUARIO-BICHO-COMBATE_USUARIO]
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('[FK_USUARIO-CAPTURA-BICHO_BICHO]') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1) 
ALTER TABLE [USUARIO-CAPTURA-BICHO] DROP CONSTRAINT [FK_USUARIO-CAPTURA-BICHO_BICHO]
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('[FK_USUARIO-CAPTURA-BICHO_UBICACIÓN]') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1) 
ALTER TABLE [USUARIO-CAPTURA-BICHO] DROP CONSTRAINT [FK_USUARIO-CAPTURA-BICHO_UBICACIÓN]
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('[FK_USUARIO-CAPTURA-BICHO_USUARIO]') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1) 
ALTER TABLE [USUARIO-CAPTURA-BICHO] DROP CONSTRAINT [FK_USUARIO-CAPTURA-BICHO_USUARIO]
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('[ATAQUE]') AND OBJECTPROPERTY(id, 'IsUserTable') = 1) 
DROP TABLE [ATAQUE]
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('[ATAQUE-POR-APRENDER]') AND OBJECTPROPERTY(id, 'IsUserTable') = 1) 
DROP TABLE [ATAQUE-POR-APRENDER]
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('[BICHO]') AND OBJECTPROPERTY(id, 'IsUserTable') = 1) 
DROP TABLE [BICHO]
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('[BICHO-ATAQUE]') AND OBJECTPROPERTY(id, 'IsUserTable') = 1) 
DROP TABLE [BICHO-ATAQUE]
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('[COMBATE]') AND OBJECTPROPERTY(id, 'IsUserTable') = 1) 
DROP TABLE [COMBATE]
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('[ESPECIE]') AND OBJECTPROPERTY(id, 'IsUserTable') = 1) 
DROP TABLE [ESPECIE]
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('[ESPECIE-DEBILIDAD]') AND OBJECTPROPERTY(id, 'IsUserTable') = 1) 
DROP TABLE [ESPECIE-DEBILIDAD]
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('[ESPECIE-FORTALEZA]') AND OBJECTPROPERTY(id, 'IsUserTable') = 1) 
DROP TABLE [ESPECIE-FORTALEZA]
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('[EVOLUCION]') AND OBJECTPROPERTY(id, 'IsUserTable') = 1) 
DROP TABLE [EVOLUCION]
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('[INTERCAMBIO]') AND OBJECTPROPERTY(id, 'IsUserTable') = 1) 
DROP TABLE [INTERCAMBIO]
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('[RONDA]') AND OBJECTPROPERTY(id, 'IsUserTable') = 1) 
DROP TABLE [RONDA]
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('[RONDA-ATAQUE-BICHO]') AND OBJECTPROPERTY(id, 'IsUserTable') = 1) 
DROP TABLE [RONDA-ATAQUE-BICHO]
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('[TIPOBICHO]') AND OBJECTPROPERTY(id, 'IsUserTable') = 1) 
DROP TABLE [TIPOBICHO]
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('[UBICACIÓN]') AND OBJECTPROPERTY(id, 'IsUserTable') = 1) 
DROP TABLE [UBICACIÓN]
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('[USUARIO]') AND OBJECTPROPERTY(id, 'IsUserTable') = 1) 
DROP TABLE [USUARIO]
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('[USUARIO-BICHO]') AND OBJECTPROPERTY(id, 'IsUserTable') = 1) 
DROP TABLE [USUARIO-BICHO]
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('[USUARIO-BICHO-COMBATE]') AND OBJECTPROPERTY(id, 'IsUserTable') = 1) 
DROP TABLE [USUARIO-BICHO-COMBATE]
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('[USUARIO-CAPTURA-BICHO]') AND OBJECTPROPERTY(id, 'IsUserTable') = 1) 
DROP TABLE [USUARIO-CAPTURA-BICHO]
;

CREATE TABLE [ATAQUE]
(
	[ID] int NOT NULL,
	[Descripción] varchar(50) NOT NULL,
	[Daño] int NOT NULL
)
;

CREATE TABLE [ATAQUE-POR-APRENDER]
(
	[Id-Especie] smallint NOT NULL,
	[Id-Ataque] int NOT NULL
)
;

CREATE TABLE [BICHO]
(
	[ID] int NOT NULL,
	[Nombre] varchar(50) NOT NULL,
	[Tipo] smallint NOT NULL,
	[Especie] smallint NOT NULL,
	[Experiencia] smallint NOT NULL
)
;

CREATE TABLE [BICHO-ATAQUE]
(
	[ID-Bicho] int NOT NULL,
	[ID-Ataque] int NOT NULL
)
;

CREATE TABLE [COMBATE]
(
	[Id-Usuario] int NOT NULL,
	[Id-Usuario2] int NOT NULL,
	[Fecha] datetime NOT NULL,
	[ID] smallint NOT NULL
)
;

CREATE TABLE [ESPECIE]
(
	[ID] smallint NOT NULL,
	[Nombre] varchar(50) NOT NULL,
	[Ataque] int NOT NULL,
	[Velocidad] int NOT NULL,
	[SaludMax] int NOT NULL
)
;

CREATE TABLE [ESPECIE-DEBILIDAD]
(
	[Id-Especie] smallint NOT NULL,
	[Id-Tipo-Debilidad] smallint NOT NULL
)
;

CREATE TABLE [ESPECIE-FORTALEZA]
(
	[Id-Especie] smallint NOT NULL,
	[Id-Tipo-Fortaleza] smallint NOT NULL
)
;

CREATE TABLE [EVOLUCION]
(
	[ID-Especie] smallint NOT NULL,
	[Evolución] smallint NOT NULL,
	[ExperenciaNecesaria] int NOT NULL
)
;

CREATE TABLE [INTERCAMBIO]
(
	[Id-Usuario] int NOT NULL,
	[Id-Bicho] int NOT NULL,
	[Id-Usuario2] int NOT NULL,
	[Fecha] datetime NOT NULL
)
;

CREATE TABLE [RONDA]
(
	[Id-BichoUsuario1] int NOT NULL,
	[Id-Bicho2Usuario2] int NOT NULL,
	[Id-Combate] smallint NOT NULL,
	[ID] int NOT NULL,
	[NúmeroRonda] smallint NOT NULL
)
;

CREATE TABLE [RONDA-ATAQUE-BICHO]
(
	[ID-Bicho] int NOT NULL,
	[ID-Ataque] int NOT NULL,
	[ID-Ronda] int NOT NULL
)
;

CREATE TABLE [TIPOBICHO]
(
	[ID] smallint NOT NULL,
	[Descripción] varchar(50) NOT NULL
)
;

CREATE TABLE [UBICACIÓN]
(
	[Id] smallint NOT NULL,
	[Descripción] varchar(50) NOT NULL
)
;

CREATE TABLE [USUARIO]
(
	[ID] int NOT NULL,
	[UserName] varchar(50) NOT NULL,
	[Nombre(s)] varchar(50) NOT NULL,
	[Apellido] varchar(50) NOT NULL,
	[Género] bit NOT NULL
)
;

CREATE TABLE [USUARIO-BICHO]
(
	[Id-Usuario] int NOT NULL,
	[Id-Bicho] int NOT NULL,
	[NivelSalud] smallint NOT NULL,
	[Experiencia] int NOT NULL
)
;

CREATE TABLE [USUARIO-BICHO-COMBATE]
(
	[ID-Usuario] int NOT NULL,
	[ID-Bicho] int NOT NULL,
	[ID-Combate] smallint NOT NULL
)
;

CREATE TABLE [USUARIO-CAPTURA-BICHO]
(
	[Id-Usuario] int NOT NULL,
	[Id-Bicho] int NOT NULL,
	[Id-Ubicación] smallint NOT NULL
)
;

ALTER TABLE [ATAQUE] 
 ADD CONSTRAINT [PK_ATAQUE]
	PRIMARY KEY CLUSTERED ([ID])
;

CREATE INDEX [IXFK_ATAQUE-POR-APRENDER_ATAQUE] 
 ON [ATAQUE-POR-APRENDER] ([Id-Ataque] ASC)
;

CREATE INDEX [IXFK_ATAQUE-POR-APRENDER_ESPECIE] 
 ON [ATAQUE-POR-APRENDER] ([Id-Especie] ASC)
;

CREATE INDEX [IXFK_BICHO_ESPECIE] 
 ON [BICHO] ([Especie] ASC)
;

CREATE INDEX [IXFK_BICHO_TIPOBICHO] 
 ON [BICHO] ([Tipo] ASC)
;

ALTER TABLE [BICHO] 
 ADD CONSTRAINT [PK_BICHO]
	PRIMARY KEY CLUSTERED ([ID])
;

CREATE INDEX [IXFK_BICHO-ATAQUE_ATAQUE] 
 ON [BICHO-ATAQUE] ([ID-Ataque] ASC)
;

CREATE INDEX [IXFK_BICHO-ATAQUE_BICHO] 
 ON [BICHO-ATAQUE] ([ID-Bicho] ASC)
;

ALTER TABLE [BICHO-ATAQUE] 
 ADD CONSTRAINT [BICHO-ATAQUE-UNICO] UNIQUE NONCLUSTERED ([ID-Bicho],[ID-Ataque])
;

CREATE INDEX [IXFK_COMBATE_USUARIO] 
 ON [COMBATE] ([Id-Usuario] ASC)
;

CREATE INDEX [IXFK_COMBATE_USUARIO_02] 
 ON [COMBATE] ([Id-Usuario2] ASC)
;

ALTER TABLE [COMBATE] 
 ADD CONSTRAINT [PK_COMBATE]
	PRIMARY KEY CLUSTERED ([ID])
;

ALTER TABLE [ESPECIE] 
 ADD CONSTRAINT [PK_ESPECIE]
	PRIMARY KEY CLUSTERED ([ID])
;

CREATE INDEX [IXFK_ESPECIE-DEBILIDAD_ESPECIE] 
 ON [ESPECIE-DEBILIDAD] ([Id-Especie] ASC)
;

CREATE INDEX [IXFK_ESPECIE-DEBILIDAD_TIPOBICHO] 
 ON [ESPECIE-DEBILIDAD] ([Id-Tipo-Debilidad] ASC)
;

ALTER TABLE [ESPECIE-DEBILIDAD] 
 ADD CONSTRAINT [ESPECIE-DEBILIDAD-UNIQUE] UNIQUE NONCLUSTERED ([Id-Especie],[Id-Tipo-Debilidad])
;

CREATE INDEX [IXFK_ESPECIE-FORTALEZA_ESPECIE] 
 ON [ESPECIE-FORTALEZA] ([Id-Especie] ASC)
;

CREATE INDEX [IXFK_ESPECIE-FORTALEZA_TIPOBICHO] 
 ON [ESPECIE-FORTALEZA] ([Id-Tipo-Fortaleza] ASC)
;

ALTER TABLE [ESPECIE-FORTALEZA] 
 ADD CONSTRAINT [ESPECIE-FORTALEZA-UNIQUE] UNIQUE NONCLUSTERED ([Id-Especie],[Id-Tipo-Fortaleza])
;

CREATE INDEX [IXFK_EVOLUCION_ESPECIE] 
 ON [EVOLUCION] ([Evolución] ASC)
;

CREATE INDEX [IXFK_EVOLUCION_ESPECIE_02] 
 ON [EVOLUCION] ([ID-Especie] ASC)
;

ALTER TABLE [EVOLUCION] 
 ADD CONSTRAINT [PK_EVOLUCION_UNICA] UNIQUE NONCLUSTERED ([Evolución],[ID-Especie],[ExperenciaNecesaria])
;

CREATE INDEX [IXFK_INTERCAMBIO_BICHO] 
 ON [INTERCAMBIO] ([Id-Bicho] ASC)
;

CREATE INDEX [IXFK_INTERCAMBIO_USUARIO] 
 ON [INTERCAMBIO] ([Id-Usuario] ASC)
;

CREATE INDEX [IXFK_INTERCAMBIO_USUARIO_02] 
 ON [INTERCAMBIO] ([Id-Usuario2] ASC)
;

CREATE INDEX [IXFK_RONDA_COMBATE] 
 ON [RONDA] ([Id-Combate] ASC)
;

ALTER TABLE [RONDA] 
 ADD CONSTRAINT [PK_RONDA]
	PRIMARY KEY CLUSTERED ([ID])
;

ALTER TABLE [RONDA] 
 ADD CONSTRAINT [RONDA_UNIC] UNIQUE NONCLUSTERED ([Id-Combate],[NúmeroRonda])
;

CREATE INDEX [IXFK_RONDA-ATAQUE-BICHO_ATAQUE] 
 ON [RONDA-ATAQUE-BICHO] ([ID-Ataque] ASC)
;

CREATE INDEX [IXFK_RONDA-ATAQUE-BICHO_BICHO] 
 ON [RONDA-ATAQUE-BICHO] ([ID-Bicho] ASC)
;

CREATE INDEX [IXFK_RONDA-ATAQUE-BICHO_RONDA] 
 ON [RONDA-ATAQUE-BICHO] ([ID-Ronda] ASC)
;

ALTER TABLE [TIPOBICHO] 
 ADD CONSTRAINT [PK_TIPOBICHO]
	PRIMARY KEY CLUSTERED ([ID])
;

ALTER TABLE [UBICACIÓN] 
 ADD CONSTRAINT [PK_UBICACIÓN]
	PRIMARY KEY CLUSTERED ([Id])
;

ALTER TABLE [USUARIO] 
 ADD CONSTRAINT [PK_USUARIO]
	PRIMARY KEY CLUSTERED ([ID])
;

CREATE INDEX [IXFK_USUARIO-BICHO_BICHO] 
 ON [USUARIO-BICHO] ([Id-Bicho] ASC)
;

CREATE INDEX [IXFK_USUARIO-BICHO_USUARIO] 
 ON [USUARIO-BICHO] ([Id-Usuario] ASC)
;

ALTER TABLE [USUARIO-BICHO] 
 ADD CONSTRAINT [USUARIO-BICHO-UNIQUE] UNIQUE NONCLUSTERED ([Id-Usuario],[Id-Bicho])
;

CREATE INDEX [IXFK_USUARIO-BICHO-COMBATE_BICHO] 
 ON [USUARIO-BICHO-COMBATE] ([ID-Bicho] ASC)
;

CREATE INDEX [IXFK_USUARIO-BICHO-COMBATE_COMBATE] 
 ON [USUARIO-BICHO-COMBATE] ([ID-Combate] ASC)
;

CREATE INDEX [IXFK_USUARIO-BICHO-COMBATE_USUARIO] 
 ON [USUARIO-BICHO-COMBATE] ([ID-Usuario] ASC)
;

CREATE INDEX [IXFK_USUARIO-CAPTURA-BICHO_BICHO] 
 ON [USUARIO-CAPTURA-BICHO] ([Id-Bicho] ASC)
;

CREATE INDEX [IXFK_USUARIO-CAPTURA-BICHO_UBICACIÓN] 
 ON [USUARIO-CAPTURA-BICHO] ([Id-Ubicación] ASC)
;

CREATE INDEX [IXFK_USUARIO-CAPTURA-BICHO_USUARIO] 
 ON [USUARIO-CAPTURA-BICHO] ([Id-Usuario] ASC)
;

ALTER TABLE [ATAQUE-POR-APRENDER] ADD CONSTRAINT [FK_ATAQUE-POR-APRENDER_ATAQUE]
	FOREIGN KEY ([Id-Ataque]) REFERENCES [ATAQUE] ([ID]) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE [ATAQUE-POR-APRENDER] ADD CONSTRAINT [FK_ATAQUE-POR-APRENDER_ESPECIE]
	FOREIGN KEY ([Id-Especie]) REFERENCES [ESPECIE] ([ID]) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE [BICHO] ADD CONSTRAINT [FK_BICHO_ESPECIE]
	FOREIGN KEY ([Especie]) REFERENCES [ESPECIE] ([ID]) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE [BICHO] ADD CONSTRAINT [FK_BICHO_TIPOBICHO]
	FOREIGN KEY ([Tipo]) REFERENCES [TIPOBICHO] ([ID]) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE [BICHO-ATAQUE] ADD CONSTRAINT [FK_BICHO-ATAQUE_ATAQUE]
	FOREIGN KEY ([ID-Ataque]) REFERENCES [ATAQUE] ([ID]) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE [BICHO-ATAQUE] ADD CONSTRAINT [FK_BICHO-ATAQUE_BICHO]
	FOREIGN KEY ([ID-Bicho]) REFERENCES [BICHO] ([ID]) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE [COMBATE] ADD CONSTRAINT [FK_COMBATE_USUARIO]
	FOREIGN KEY ([Id-Usuario]) REFERENCES [USUARIO] ([ID]) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE [COMBATE] ADD CONSTRAINT [FK_COMBATE_USUARIO_02]
	FOREIGN KEY ([Id-Usuario2]) REFERENCES [USUARIO] ([ID]) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE [ESPECIE-DEBILIDAD] ADD CONSTRAINT [FK_ESPECIE-DEBILIDAD_ESPECIE]
	FOREIGN KEY ([Id-Especie]) REFERENCES [ESPECIE] ([ID]) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE [ESPECIE-DEBILIDAD] ADD CONSTRAINT [FK_ESPECIE-DEBILIDAD_TIPOBICHO]
	FOREIGN KEY ([Id-Tipo-Debilidad]) REFERENCES [TIPOBICHO] ([ID]) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE [ESPECIE-FORTALEZA] ADD CONSTRAINT [FK_ESPECIE-FORTALEZA_ESPECIE]
	FOREIGN KEY ([Id-Especie]) REFERENCES [ESPECIE] ([ID]) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE [ESPECIE-FORTALEZA] ADD CONSTRAINT [FK_ESPECIE-FORTALEZA_TIPOBICHO]
	FOREIGN KEY ([Id-Tipo-Fortaleza]) REFERENCES [TIPOBICHO] ([ID]) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE [EVOLUCION] ADD CONSTRAINT [FK_EVOLUCION_ESPECIE]
	FOREIGN KEY ([Evolución]) REFERENCES [ESPECIE] ([ID]) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE [EVOLUCION] ADD CONSTRAINT [FK_EVOLUCION_ESPECIE_02]
	FOREIGN KEY ([ID-Especie]) REFERENCES [ESPECIE] ([ID]) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE [INTERCAMBIO] ADD CONSTRAINT [FK_INTERCAMBIO_BICHO]
	FOREIGN KEY ([Id-Bicho]) REFERENCES [BICHO] ([ID]) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE [INTERCAMBIO] ADD CONSTRAINT [FK_INTERCAMBIO_USUARIO]
	FOREIGN KEY ([Id-Usuario]) REFERENCES [USUARIO] ([ID]) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE [INTERCAMBIO] ADD CONSTRAINT [FK_INTERCAMBIO_USUARIO_02]
	FOREIGN KEY ([Id-Usuario2]) REFERENCES [USUARIO] ([ID]) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE [RONDA] ADD CONSTRAINT [FK_RONDA_COMBATE]
	FOREIGN KEY ([Id-Combate]) REFERENCES [COMBATE] ([ID]) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE [RONDA-ATAQUE-BICHO] ADD CONSTRAINT [FK_RONDA-ATAQUE-BICHO_ATAQUE]
	FOREIGN KEY ([ID-Ataque]) REFERENCES [ATAQUE] ([ID]) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE [RONDA-ATAQUE-BICHO] ADD CONSTRAINT [FK_RONDA-ATAQUE-BICHO_BICHO]
	FOREIGN KEY ([ID-Bicho]) REFERENCES [BICHO] ([ID]) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE [RONDA-ATAQUE-BICHO] ADD CONSTRAINT [FK_RONDA-ATAQUE-BICHO_RONDA]
	FOREIGN KEY ([ID-Ronda]) REFERENCES [RONDA] ([ID]) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE [USUARIO-BICHO] ADD CONSTRAINT [FK_USUARIO-BICHO_BICHO]
	FOREIGN KEY ([Id-Bicho]) REFERENCES [BICHO] ([ID]) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE [USUARIO-BICHO] ADD CONSTRAINT [FK_USUARIO-BICHO_USUARIO]
	FOREIGN KEY ([Id-Usuario]) REFERENCES [USUARIO] ([ID]) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE [USUARIO-BICHO-COMBATE] ADD CONSTRAINT [FK_USUARIO-BICHO-COMBATE_BICHO]
	FOREIGN KEY ([ID-Bicho]) REFERENCES [BICHO] ([ID]) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE [USUARIO-BICHO-COMBATE] ADD CONSTRAINT [FK_USUARIO-BICHO-COMBATE_COMBATE]
	FOREIGN KEY ([ID-Combate]) REFERENCES [COMBATE] ([ID]) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE [USUARIO-BICHO-COMBATE] ADD CONSTRAINT [FK_USUARIO-BICHO-COMBATE_USUARIO]
	FOREIGN KEY ([ID-Usuario]) REFERENCES [USUARIO] ([ID]) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE [USUARIO-CAPTURA-BICHO] ADD CONSTRAINT [FK_USUARIO-CAPTURA-BICHO_BICHO]
	FOREIGN KEY ([Id-Bicho]) REFERENCES [BICHO] ([ID]) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE [USUARIO-CAPTURA-BICHO] ADD CONSTRAINT [FK_USUARIO-CAPTURA-BICHO_UBICACIÓN]
	FOREIGN KEY ([Id-Ubicación]) REFERENCES [UBICACIÓN] ([Id]) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE [USUARIO-CAPTURA-BICHO] ADD CONSTRAINT [FK_USUARIO-CAPTURA-BICHO_USUARIO]
	FOREIGN KEY ([Id-Usuario]) REFERENCES [USUARIO] ([ID]) ON DELETE No Action ON UPDATE No Action
;
