USE BICHOS
GO 
CREATE TABLE [ATAQUE]
(
	[ID] int NOT NULL,
	[Descripción] varchar(50) NOT NULL,
	[Daño] int NOT NULL,
	[Tipo] smallint NOT NULL
)
;

CREATE TABLE [ATAQUE-POR-APRENDER]
(
	[Id-Especie] smallint NOT NULL,
	[Id-Ataque] int NOT NULL
)
;

CREATE TABLE [BICHO]
(
	[ID] int NOT NULL,
	[Nombre] varchar(50) NOT NULL,
	[Especie] smallint NOT NULL,
	[Experiencia] smallint NOT NULL,
	[Propietario] int NOT NULL
)
;

CREATE TABLE [BICHO-ATAQUE]
(
	[ID-Bicho] int NOT NULL,
	[ID-Ataque] int NOT NULL
)
;

CREATE TABLE [COMBATE]
(
	[Id-Usuario] int NOT NULL,
	[Id-Usuario2] int NOT NULL,
	[Fecha] datetime NOT NULL,
	[ID] smallint IDENTITY(1,1) NOT NULL,
	[Ganador] int NOT NULL
)
;

CREATE TABLE [ESPECIE]
(
	[ID] smallint NOT NULL,
	[Nombre] varchar(50) NOT NULL,
	[Ataque] int NOT NULL,
	[Velocidad] int NOT NULL,
	[SaludMax] int NOT NULL,
	[Tipo] smallint NOT NULL
)
;

CREATE TABLE [EVOLUCION]
(
	[ID-Especie] smallint NOT NULL,
	[Evolución] smallint NOT NULL,
	[ExperenciaNecesaria] int NOT NULL
)
;

CREATE TABLE [INTERCAMBIO]
(
	[Id-Usuario1] int NOT NULL,
	[Id-Bicho1] int NOT NULL,
	[Id-Usuario2] int NOT NULL,
	[Id-Bicho2] int NOT NULL,
	[Fecha] datetime NOT NULL
)
;

CREATE TABLE [RONDA]
(
	[Id-BichoUsuario1] int NOT NULL,
	[Id-Bicho2Usuario2] int NOT NULL,
	[Id-Combate] smallint NOT NULL,
	[ID] int IDENTITY(1,1) NOT NULL,
	[NúmeroRonda] smallint NOT NULL
)
;

CREATE TABLE [RONDA-ATAQUE-BICHO]
(
	[ID-AtaqueBicho1] int NOT NULL,
	[ID-AtaqueBicho2] int NOT NULL,
	[ID-Ronda] int NOT NULL
)
;

CREATE TABLE [TIPO-DEBILIDAD]
(
	[Id-Tipo] smallint NOT NULL,
	[Id-Tipo-Debilidad] smallint NOT NULL
)
;

CREATE TABLE [TIPO-FORTALEZA]
(
	[Id-Tipo] smallint NOT NULL,
	[Id-Tipo-Fortaleza] smallint NOT NULL
)
;

CREATE TABLE [TIPOBICHO]
(
	[ID] smallint NOT NULL,
	[Descripción] varchar(50) NOT NULL
)
;

CREATE TABLE [UBICACIÓN]
(
	[Id] smallint NOT NULL,
	[Descripción] varchar(50) NOT NULL
)
;

CREATE TABLE [USUARIO]
(
	[ID] int NOT NULL,
	[UserName] varchar(50) NOT NULL,
	[Nombre(s)] varchar(50) NOT NULL,
	[Apellido] varchar(50) NOT NULL,
	[Género] bit NOT NULL
)
;

CREATE TABLE [USUARIO-BICHO-COMBATE]
(
	[ID-Usuario] int NOT NULL,
	[ID-Bicho1] int NOT NULL,
	[ID-Bicho2] int NOT NULL,
	[ID-Bicho3] int NOT NULL,
	[ID-Combate] smallint NOT NULL
)
;

CREATE TABLE [USUARIO-CAPTURA-BICHO]
(
	[Id-Usuario] int NOT NULL,
	[Id-Bicho] int NOT NULL,
	[Id-Ubicación] smallint NOT NULL,
	[Fecha] date NOT NULL
)
;

ALTER TABLE [ATAQUE] 
 ADD CONSTRAINT [PK_ATAQUE]
	PRIMARY KEY CLUSTERED ([ID])
;

CREATE INDEX [IXFK_ATAQUE-POR-APRENDER_ATAQUE] 
 ON [ATAQUE-POR-APRENDER] ([Id-Ataque] ASC)
;

CREATE INDEX [IXFK_TIPO] 
 ON [ATAQUE] ([Tipo] ASC)
;

CREATE INDEX [IXFK_ATAQUE-POR-APRENDER_ESPECIE] 
 ON [ATAQUE-POR-APRENDER] ([Id-Especie] ASC)
;

CREATE INDEX [IXFK_BICHO_ESPECIE] 
 ON [BICHO] ([Especie] ASC)
;

CREATE INDEX [IXFK_BICHO_USUARIO] 
 ON [BICHO] ([Propietario] ASC)
;

ALTER TABLE [BICHO] 
 ADD CONSTRAINT [PK_BICHO]
	PRIMARY KEY CLUSTERED ([ID])
;

CREATE INDEX [IXFK_BICHO-ATAQUE_ATAQUE] 
 ON [BICHO-ATAQUE] ([ID-Ataque] ASC)
;

CREATE INDEX [IXFK_BICHO-ATAQUE_BICHO] 
 ON [BICHO-ATAQUE] ([ID-Bicho] ASC)
;

CREATE INDEX [IXFK_COMBATE_USUARIO] 
 ON [COMBATE] ([Id-Usuario] ASC)
;

CREATE INDEX [IXFK_COMBATE_USUARIO_02] 
 ON [COMBATE] ([Id-Usuario2] ASC)
;

CREATE INDEX [IXFK_COMBATE_USUARIO_03] 
 ON [COMBATE] ([Ganador] ASC)
;

ALTER TABLE [COMBATE] 
 ADD CONSTRAINT [PK_COMBATE]
	PRIMARY KEY CLUSTERED ([ID])
;

CREATE INDEX [IXFK_ESPECIE_TIPOBICHO] 
 ON [ESPECIE] ([Tipo] ASC)
;

ALTER TABLE [ESPECIE] 
 ADD CONSTRAINT [PK_ESPECIE]
	PRIMARY KEY CLUSTERED ([ID])
;

CREATE INDEX [IXFK_EVOLUCION_ESPECIE] 
 ON [EVOLUCION] ([Evolución] ASC)
;

CREATE INDEX [IXFK_EVOLUCION_ESPECIE_02] 
 ON [EVOLUCION] ([ID-Especie] ASC)
;

ALTER TABLE [EVOLUCION] 
 ADD CONSTRAINT [PK_EVOLUCION_UNICA] UNIQUE NONCLUSTERED ([Evolución],[ID-Especie],[ExperenciaNecesaria])
;

CREATE INDEX [IXFK_INTERCAMBIO_BICHO1] 
 ON [INTERCAMBIO] ([Id-Bicho1] ASC)
;

CREATE INDEX [IXFK_INTERCAMBIO_BICHO2] 
 ON [INTERCAMBIO] ([Id-Bicho2] ASC)

CREATE INDEX [IXFK_INTERCAMBIO_USUARIO] 
 ON [INTERCAMBIO] ([Id-Usuario1] ASC)
;

CREATE INDEX [IXFK_INTERCAMBIO_USUARIO_02] 
 ON [INTERCAMBIO] ([Id-Usuario2] ASC)
;

CREATE INDEX [IXFK_RONDA_COMBATE] 
 ON [RONDA] ([Id-Combate] ASC)
;

ALTER TABLE [RONDA] 
 ADD CONSTRAINT [PK_RONDA]
	PRIMARY KEY CLUSTERED ([ID])
;

ALTER TABLE [RONDA] 
 ADD CONSTRAINT [RONDA_UNIC] UNIQUE NONCLUSTERED ([Id-Combate],[NúmeroRonda])
;

CREATE INDEX [IXFK_RONDA-ATAQUE-BICHO_ATAQUE] 
 ON [RONDA-ATAQUE-BICHO] ([ID-AtaqueBicho2] ASC)
;

CREATE INDEX [IXFK_RONDA-ATAQUE-BICHO_ATAQUE_02] 
 ON [RONDA-ATAQUE-BICHO] ([ID-AtaqueBicho1] ASC)
;

CREATE INDEX [IXFK_RONDA-ATAQUE-BICHO_RONDA] 
 ON [RONDA-ATAQUE-BICHO] ([ID-Ronda] ASC)
;

CREATE INDEX [IXFK_ESPECIE-DEBILIDAD_TIPOBICHO] 
 ON [TIPO-DEBILIDAD] ([Id-Tipo] ASC)
;

CREATE INDEX [IXFK_ESPECIE-DEBILIDAD_TIPOBICHO_02] 
 ON [TIPO-DEBILIDAD] ([Id-Tipo-Debilidad] ASC)
;

ALTER TABLE [TIPO-DEBILIDAD] 
 ADD CONSTRAINT [UNIQUE_TIPO-DEBILIDAD] UNIQUE NONCLUSTERED ([Id-Tipo],[Id-Tipo-Debilidad])
;

CREATE INDEX [IXFK_TIPO-FORTALEZA_TIPOBICHO] 
 ON [TIPO-FORTALEZA] ([Id-Tipo] ASC)
;

CREATE INDEX [IXFK_TIPO-FORTALEZA_TIPOBICHO_02] 
 ON [TIPO-FORTALEZA] ([Id-Tipo-Fortaleza] ASC)
;

ALTER TABLE [TIPO-FORTALEZA] 
 ADD CONSTRAINT [TIPO-FORTALEZA-UNIQUE] UNIQUE NONCLUSTERED ([Id-Tipo],[Id-Tipo-Fortaleza])
;

ALTER TABLE [TIPOBICHO] 
 ADD CONSTRAINT [PK_TIPOBICHO]
	PRIMARY KEY CLUSTERED ([ID])
;

ALTER TABLE [UBICACIÓN] 
 ADD CONSTRAINT [PK_UBICACIÓN]
	PRIMARY KEY CLUSTERED ([Id])
;

ALTER TABLE [USUARIO] 
 ADD CONSTRAINT [PK_USUARIO]
	PRIMARY KEY CLUSTERED ([ID])
;

CREATE INDEX [IXFK_USUARIO-BICHO-COMBATE_BICHO] 
 ON [USUARIO-BICHO-COMBATE] ([ID-Bicho1] ASC)
;
CREATE INDEX [IXFK_USUARIO-BICHO-COMBATE_BICHO2] 
 ON [USUARIO-BICHO-COMBATE] ([ID-Bicho2] ASC)
;
CREATE INDEX [IXFK_USUARIO-BICHO-COMBATE_BICHO3] 
 ON [USUARIO-BICHO-COMBATE] ([ID-Bicho3] ASC)
;
CREATE INDEX [IXFK_USUARIO-BICHO-COMBATE_COMBATE] 
 ON [USUARIO-BICHO-COMBATE] ([ID-Combate] ASC)
;

CREATE INDEX [IXFK_USUARIO-BICHO-COMBATE_USUARIO] 
 ON [USUARIO-BICHO-COMBATE] ([ID-Usuario] ASC)
;

CREATE INDEX [IXFK_USUARIO-CAPTURA-BICHO_BICHO1] 
 ON [USUARIO-CAPTURA-BICHO] ([Id-Bicho] ASC)

;

CREATE INDEX [IXFK_USUARIO-CAPTURA-BICHO_UBICACIÓN] 
 ON [USUARIO-CAPTURA-BICHO] ([Id-Ubicación] ASC)
;

CREATE INDEX [IXFK_USUARIO-CAPTURA-BICHO_USUARIO] 
 ON [USUARIO-CAPTURA-BICHO] ([Id-Usuario] ASC)
;

ALTER TABLE [ATAQUE-POR-APRENDER] ADD CONSTRAINT [FK_ATAQUE-POR-APRENDER_ATAQUE]
	FOREIGN KEY ([Id-Ataque]) REFERENCES [ATAQUE] ([ID]) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE [ATAQUE] ADD CONSTRAINT [FK_TIPO-ATAQUE]
	FOREIGN KEY ([Tipo]) REFERENCES [TIPOBICHO] ([ID]) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE [ATAQUE-POR-APRENDER] ADD CONSTRAINT [FK_ATAQUE-POR-APRENDER_ESPECIE]
	FOREIGN KEY ([Id-Especie]) REFERENCES [ESPECIE] ([ID]) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE [BICHO] ADD CONSTRAINT [FK_BICHO_ESPECIE]
	FOREIGN KEY ([Especie]) REFERENCES [ESPECIE] ([ID]) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE [BICHO] ADD CONSTRAINT [FK_BICHO_USUARIO]
	FOREIGN KEY ([Propietario]) REFERENCES [USUARIO] ([ID]) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE [BICHO-ATAQUE] ADD CONSTRAINT [FK_BICHO-ATAQUE_ATAQUE]
	FOREIGN KEY ([ID-Ataque]) REFERENCES [ATAQUE] ([ID]) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE [BICHO-ATAQUE] ADD CONSTRAINT [FK_BICHO-ATAQUE_BICHO]
	FOREIGN KEY ([ID-Bicho]) REFERENCES [BICHO] ([ID]) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE [COMBATE] ADD CONSTRAINT [FK_COMBATE_USUARIO]
	FOREIGN KEY ([Id-Usuario]) REFERENCES [USUARIO] ([ID]) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE [COMBATE] ADD CONSTRAINT [FK_COMBATE_USUARIO_02]
	FOREIGN KEY ([Id-Usuario2]) REFERENCES [USUARIO] ([ID]) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE [COMBATE] ADD CONSTRAINT [FK_COMBATE_USUARIO_03]
	FOREIGN KEY ([Ganador]) REFERENCES [USUARIO] ([ID]) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE [ESPECIE] ADD CONSTRAINT [FK_ESPECIE_TIPOBICHO]
	FOREIGN KEY ([Tipo]) REFERENCES [TIPOBICHO] ([ID]) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE [EVOLUCION] ADD CONSTRAINT [FK_EVOLUCION_ESPECIE]
	FOREIGN KEY ([Evolución]) REFERENCES [ESPECIE] ([ID]) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE [EVOLUCION] ADD CONSTRAINT [FK_EVOLUCION_ESPECIE_02]
	FOREIGN KEY ([ID-Especie]) REFERENCES [ESPECIE] ([ID]) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE [INTERCAMBIO] ADD CONSTRAINT [FK_INTERCAMBIO_BICHO1]
	FOREIGN KEY ([Id-Bicho1]) REFERENCES [BICHO] ([ID]) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE [INTERCAMBIO] ADD CONSTRAINT [FK_INTERCAMBIO_BICHO2]
	FOREIGN KEY ([Id-Bicho1]) REFERENCES [BICHO] ([ID]) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE [INTERCAMBIO] ADD CONSTRAINT [FK_INTERCAMBIO_USUARIO1]
	FOREIGN KEY ([Id-Usuario1]) REFERENCES [USUARIO] ([ID]) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE [INTERCAMBIO] ADD CONSTRAINT [FK_INTERCAMBIO_USUARIO_2]
	FOREIGN KEY ([Id-Usuario2]) REFERENCES [USUARIO] ([ID]) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE [RONDA] ADD CONSTRAINT [FK_RONDA_COMBATE]
	FOREIGN KEY ([Id-Combate]) REFERENCES [COMBATE] ([ID]) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE [RONDA-ATAQUE-BICHO] ADD CONSTRAINT [FK_RONDA-ATAQUE-BICHO_ATAQUE]
	FOREIGN KEY ([ID-AtaqueBicho2]) REFERENCES [ATAQUE] ([ID]) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE [RONDA-ATAQUE-BICHO] ADD CONSTRAINT [FK_RONDA-ATAQUE-BICHO_ATAQUE_02]
	FOREIGN KEY ([ID-AtaqueBicho1]) REFERENCES [ATAQUE] ([ID]) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE [RONDA-ATAQUE-BICHO] ADD CONSTRAINT [FK_RONDA-ATAQUE-BICHO_RONDA]
	FOREIGN KEY ([ID-Ronda]) REFERENCES [RONDA] ([ID]) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE [TIPO-DEBILIDAD] ADD CONSTRAINT [FK_ESPECIE-DEBILIDAD_TIPOBICHO]
	FOREIGN KEY ([Id-Tipo]) REFERENCES [TIPOBICHO] ([ID]) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE [TIPO-DEBILIDAD] ADD CONSTRAINT [FK_ESPECIE-DEBILIDAD_TIPOBICHO_02]
	FOREIGN KEY ([Id-Tipo-Debilidad]) REFERENCES [TIPOBICHO] ([ID]) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE [TIPO-FORTALEZA] ADD CONSTRAINT [FK_TIPO-FORTALEZA_TIPOBICHO_02]
	FOREIGN KEY ([Id-Tipo-Fortaleza]) REFERENCES [TIPOBICHO] ([ID]) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE [USUARIO-BICHO-COMBATE] ADD CONSTRAINT [FK_USUARIO-BICHO-COMBATE_BICHO1]
	FOREIGN KEY ([ID-Bicho1]) REFERENCES [BICHO] ([ID]) ON DELETE No Action ON UPDATE No Action
;
ALTER TABLE [USUARIO-BICHO-COMBATE] ADD CONSTRAINT [FK_USUARIO-BICHO-COMBATE_BICHO2]
	FOREIGN KEY ([ID-Bicho2]) REFERENCES [BICHO] ([ID]) ON DELETE No Action ON UPDATE No Action
;
ALTER TABLE [USUARIO-BICHO-COMBATE] ADD CONSTRAINT [FK_USUARIO-BICHO-COMBATE_BICHO3]
	FOREIGN KEY ([ID-Bicho3]) REFERENCES [BICHO] ([ID]) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE [USUARIO-BICHO-COMBATE] ADD CONSTRAINT [FK_USUARIO-BICHO-COMBATE_COMBATE]
	FOREIGN KEY ([ID-Combate]) REFERENCES [COMBATE] ([ID]) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE [USUARIO-BICHO-COMBATE] ADD CONSTRAINT [FK_USUARIO-BICHO-COMBATE_USUARIO]
	FOREIGN KEY ([ID-Usuario]) REFERENCES [USUARIO] ([ID]) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE [USUARIO-CAPTURA-BICHO] ADD CONSTRAINT [FK_USUARIO-CAPTURA-BICHO_BICHO]
	FOREIGN KEY ([Id-Bicho]) REFERENCES [BICHO] ([ID]) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE [USUARIO-CAPTURA-BICHO] ADD CONSTRAINT [FK_USUARIO-CAPTURA-BICHO_UBICACIÓN]
	FOREIGN KEY ([Id-Ubicación]) REFERENCES [UBICACIÓN] ([Id]) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE [USUARIO-CAPTURA-BICHO] ADD CONSTRAINT [FK_USUARIO-CAPTURA-BICHO_USUARIO]
	FOREIGN KEY ([Id-Usuario]) REFERENCES [USUARIO] ([ID]) ON DELETE No Action ON UPDATE No Action
;
