--CONSULTAS--

--CONSULTAS NO TRIVIALES

--CONSULTA 1 MOSTRAR EL PROMEDIO DE ATAQUE DE ESPECIE POR TIPO
SELECT T.ID,T.Descripción, AVG (E.Ataque)[PROMEDIO-ATAQUE]FROM ESPECIE E
INNER JOIN TIPOBICHO T ON E.Tipo=T.ID
group by T.Descripción,T.ID

--CONSULTA 2 MOSTRAR EL PROMEDIO DE EXPERENCIA DE BICHO ESPECIE
SELECT E.Nombre,T.Descripción, AVG (B.Experiencia)[PROMEDIO-EXPERIENCIA]FROM ESPECIE E
INNER JOIN TIPOBICHO T ON E.Tipo=T.ID
INNER JOIN BICHO B ON B.Especie=E.ID
group by T.Descripción,E.Nombre

--CONSULTA 3 MOSTRAR AQUELLOS USUARIOS QUE NO HAYAN CAPTURADO Y QUE SEA PROPIETARIO DE AL MENOS 1 BICHO
SELECT U.ID FROM USUARIO U INNER JOIN BICHO B ON U.ID=B.Propietario
GROUP BY  U.ID
HAVING COUNT(B.Propietario) >=1 
EXCEPT 
SELECT [Id-Usuario] FROM [USUARIO-CAPTURA-BICHO]

--CONSULTA 4 MOSTRAR AQUELLOS ESPECIES QUE NO TENGAN EVOLUCIÓN
SELECT E.ID FROM ESPECIE E
EXCEPT (SELECT E.[ID-Especie] FROM EVOLUCION  E)

SELECT * FROM EVOLUCION
--CONSULTA 5 MOSTRAR LOS BICHOS QUE HAYAN PARTICIPADO EN COMBATES, PERO NO HEN UNA RONDAS
SELECT B.ID  FROM BICHO B 
INTERSECT
SELECT UBC.[ID-Bicho] FROM [USUARIO-BICHO-COMBATE]  UBC
EXCEPT 
SELECT R.[Id-BichoUsuario1] FROM RONDA R
EXCEPT 
SELECT R.[Id-Bicho2Usuario2] FROM RONDA R
--CONSULTA 6 MOSTRAR AQUELLOS BICHOS QUE HAN SIDO INTERCAMBIADOS 2 O MAS VECES
SELECT B.ID,B.Nombre,COUNT(I.[Id-Bicho1]) [CANTIDAD]FROM BICHO B INNER JOIN INTERCAMBIO I
ON B.ID=I.[Id-Bicho1] OR B.ID=I.[Id-Bicho2] 
group by B.ID,B.Nombre
HAVING count(I.[Id-Bicho1]) >= 2
--CONSULTA 7 MOSTRAR AQUELLOS BICHOS QUE NO HAYAN PARTICIPADO EN UN COMBATE
SELECT B.ID  FROM BICHO B 
EXCEPT
SELECT UBC.[ID-Bicho] FROM [USUARIO-BICHO-COMBATE]  UBC

--CONSULTA 8 MOSTRAR AQUELLOS BICHOS QUE HAYAN PARTICIPADO EN 2 O MAS COMBATES
SELECT B.ID,B.Nombre,COUNT(UBC.[ID-Bicho]) [CANTIDAD]FROM BICHO B INNER JOIN [USUARIO-BICHO-COMBATE] UBC
ON B.ID=UBC.[ID-Bicho]
group by B.ID,B.Nombre
HAVING count(UBC.[ID-Bicho]) >= 2
--CONSULTA 9 MOSTRAR EL ID DEL USUARIO QUE HAYA GANADO EL UNICO COMBATE DONDE COMBATIO
SELECT U.ID from USUARIO U INNER JOIN COMBATE C
ON U.ID=C.[Id-Usuario] OR U.ID=C.[Id-Usuario2] 
GROUP BY U.ID
HAVING COUNT(C.[Id-Usuario])=1
INTERSECT 
SELECT C.Ganador FROM COMBATE C

--CONSULTA 10 MOSTRAR EL ATAQUE QUE UTILIZO EL BICHO1 EN X RONDA, QUE DAÑO CAUSO Y SU PROPIETARIO
SELECT B.Propietario,B.ID, R.NúmeroRonda, B.Nombre[BICHO],A.Descripción[ATAQUE],A.Daño FROM RONDA R INNER JOIN [RONDA-ATAQUE-BICHO] RAB ON R.ID=RAB.[ID-Ronda]
INNER JOIN BICHO B ON B.ID = R.[Id-BichoUsuario1]
INNER JOIN ATAQUE A ON A.ID=RAB.[ID-AtaqueBicho1]
WHERE R.ID = 1
--CONSULTA 11 MOSTRAR AQUELLOS BICHOS CUYO ATAQUE SOLAMENTE SEA " "
SELECT B.ID FROM BICHO B INNER JOIN [BICHO-ATAQUE] BA ON B.ID=BA.[ID-Bicho]
INNER JOIN ATAQUE A ON A.ID=BA.[ID-Ataque]
EXCEPT
SELECT BA.[ID-Bicho] FROM [BICHO-ATAQUE] BA INNER JOIN ATAQUE A ON  BA.[ID-Ataque]=A.ID
WHERE A.Descripción NOT LIKE 'FOCO RESPLANDOR'
--CONSULTA 12 MOSTRAR AQUELLOS TIPOS QUE NO TENGAN DEBILIDAD ANTE OTROS TIPOS
SELECT T.ID FROM  TIPOBICHO T 
EXCEPT 
SELECT T.[Id-Tipo] FROM [TIPO-DEBILIDAD] T

--CONSULTA 13 MOSTRAR AQUELLOS TIPOS QUE SOLAMENTE TENGAN DEBILIDAD ANTE TIPO X
SELECT T.ID FROM  TIPOBICHO T 
EXCEPT 
SELECT T.[Id-Tipo] FROM [TIPO-DEBILIDAD] T
WHERE NOT T.[Id-Tipo-Debilidad]=1
	
--CONSULTA 14 MOSTRAR AQUELLOS TIPOS QUE SOLAMENTE TENGAN 2 O MAS DEBILIDADES ANTE OTROS TIPOS
SELECT T.ID,COUNT(TD.[Id-Tipo-Debilidad]) AS CANTIDAD FROM  TIPOBICHO T INNER JOIN [TIPO-DEBILIDAD] TD
ON T.ID=TD.[Id-Tipo]
group by T.ID
HAVING COUNT(TD.[Id-Tipo-Debilidad]) >=2
--CONSULTA 15 CUANTOS BICHOS CAPTURARON LOS USUARIOS DURANTE UN LAPSO DE TIEMPO
SELECT U.UserName,COUNT(UCB.[Id-Usuario]) [BICHOS CAPTURADOS] FROM [USUARIO-CAPTURA-BICHO] UCB 
INNER JOIN USUARIO U ON U.ID=UCB.[Id-Usuario]
WHERE  UCB.fecha BETWEEN '20170101' AND '20170808'
GROUP BY U.UserName

--CONSULTA 16 MOSTRAR AQUELLOS USUARIOS QUE NO HAYAN CAPTURADO Y QUE SEA PROPIETARIO DE 0 BICHOS 
SELECT ID FROM USUARIO
EXCEPT 
SELECT [Id-Usuario] FROM [USUARIO-CAPTURA-BICHO]
EXCEPT 
SELECT Propietario FROM BICHO

--CONSULTA 17 MOSTRAR AQUELLOS TIPOS QUE NO TENGAN FORTALEZA ANTE OTROS TIPOS
SELECT * FROM [TIPO-FORTALEZA] 
SELECT T.ID FROM TIPOBICHO T
EXCEPT
SELECT T.[Id-Tipo] FROM [TIPO-FORTALEZA] T

--CONSULTA 18 MOSTRAR LA UBICACIÓN DONDE HAN SIDO CAPTURADOS MAYOR DE 5 BICHOS
SELECT UCB.[Id-Ubicación],U.Descripción, COUNT(UCB.[Id-Ubicación]) AS [BICHOS CAPTURADOS] FROM [USUARIO-CAPTURA-BICHO] UCB
INNER JOIN UBICACIÓN U ON U.Id=UCB.[Id-Ubicación]
GROUP BY UCB.[Id-Ubicación],U.Descripción
HAVING COUNT(UCB.[Id-Ubicación])>5


--CONSULTA 19 MOSTRAR LOS USUARIOS HAYAN PARTICIPADO EN AL MENOS UN COMBATE PERO NO HAYAN GANADO COMBATES
SELECT U.ID FROM USUARIO U
EXCEPT
SELECT C.[Id-Usuario] FROM COMBATE C
EXCEPT
SELECT C.[Id-Usuario2] FROM COMBATE C
--CONSULTA 20 MOSTRAR LOS USUARIOS QUE NO HAN PARTICIPADO EN UN INTERCAMBIO PERO SI UN COMBATE
SELECT U.ID FROM USUARIO U 
EXCEPT 
SELECT I.[Id-Usuario1] FROM INTERCAMBIO I
EXCEPT 
SELECT I.[Id-Usuario2] FROM INTERCAMBIO I
INTERSECT
SELECT C.[Id-Usuario] FROM COMBATE C
INTERSECT
SELECT C.[Id-Usuario2] FROM COMBATE C

--CONSULTAS TRIVIALES

--CONSULTA 1 MOSTRAR EL BICHO MAS VELOZ, SU NOMBRE, ID

--CONSULTA 2 MOSTRAR AQUELLOS BICHOS QUE TENGAN 2 0 MÁS EVOLUCIONES

--CONSULTA 3 MOSTAR CANTIDAD DE BICHOS, POR TIPO

--CONSULTA 4 CUANTOS BICHOS CONTIENE CADA USUARIO

--VISTAS--
CREATE VIEW VISTABICHOS
AS
SELECT ID,NOMBRE
FROM BICHO

select * from  VISTABICHOS

CREATE VIEW [VISTA-ATAQUES-BICHOS]
AS
SELECT BA.[ID-Bicho],Ba.[Id-Ataque]
FROM [BICHO-ATAQUE] BA

CREATE VIEW [VISTA-ATAQUE]
AS
SELECT ID,DESCRIPCION
FROM [ATAQUE] A

select * from [VISTA-ATAQUES-BICHOS]
select * from [VISTA-ATAQUE]
select VB.NOMBRE,VAB.[Id-Ataque] from VISTABICHOS VB
INNER JOIN [VISTA-ATAQUES-BICHOS] VAB ON VAB.[ID-Bicho]=VB.ID
INNER JOIN [VISTA-ATAQUE] VA ON VA.ID=VAB.[Id-Ataque]
where VB.ID=1