--CONSULTAS--

--CONSULTAS NO TRIVIALES

--CONSULTA 1 MOSTRAR EL PROMEDIO DE ATAQUE DE ESPECIE POR TIPO
SELECT T.ID,T.Descripción, AVG (E.Ataque)[PROMEDIO-ATAQUE]FROM ESPECIE E
INNER JOIN TIPOBICHO T ON E.Tipo=T.ID
group by T.Descripción,T.ID

--CONSULTA 2 MOSTRAR EL PROMEDIO DE EXPERENCIA DE BICHO ESPECIE
SELECT E.Nombre,T.Descripción, AVG (B.Experiencia)[PROMEDIO-EXPERIENCIA]FROM ESPECIE E
INNER JOIN TIPOBICHO T ON E.Tipo=T.ID
INNER JOIN BICHO B ON B.Especie=E.ID
group by T.Descripción,E.Nombre

--CONSULTA 3 MOSTRAR AQUELLOS USUARIOS QUE NO HAYAN CAPTURADO Y QUE SEA PROPIETARIO DE AL MENOS 1 BICHO
SELECT U.ID FROM USUARIO U INNER JOIN BICHO B ON U.ID=B.Propietario
GROUP BY  U.ID
HAVING COUNT(B.Propietario) >=1 
EXCEPT 
SELECT [Id-Usuario] FROM [USUARIO-CAPTURA-BICHO]

--CONSULTA 4 MOSTRAR AQUELLOS ESPECIES QUE NO TENGAN EVOLUCIÓN
SELECT E.ID FROM ESPECIE E
EXCEPT (SELECT E.[ID-Especie] FROM EVOLUCION  E)

SELECT * FROM EVOLUCION
--CONSULTA 5 MOSTRAR LOS BICHOS QUE HAYAN PARTICIPADO EN COMBATES, PERO NO HEN UNA RONDAS
SELECT B.ID  FROM BICHO B 
INTERSECT
SELECT UBC.[ID-Bicho] FROM [USUARIO-BICHO-COMBATE]  UBC
EXCEPT 
SELECT R.[Id-BichoUsuario1] FROM RONDA R
EXCEPT 
SELECT R.[Id-Bicho2Usuario2] FROM RONDA R
--CONSULTA 6 MOSTRAR AQUELLOS BICHOS QUE HAN SIDO INTERCAMBIADOS 2 O MAS VECES
SELECT B.ID,B.Nombre,COUNT(I.[Id-Bicho1]) [CANTIDAD]FROM BICHO B INNER JOIN INTERCAMBIO I
ON B.ID=I.[Id-Bicho1] OR B.ID=I.[Id-Bicho2] 
group by B.ID,B.Nombre
HAVING count(I.[Id-Bicho1]) >= 2
--CONSULTA 7 MOSTRAR AQUELLOS BICHOS QUE NO HAYAN PARTICIPADO EN UN COMBATE
SELECT B.ID  FROM BICHO B 
EXCEPT
SELECT UBC.[ID-Bicho] FROM [USUARIO-BICHO-COMBATE]  UBC

--CONSULTA 8 MOSTRAR AQUELLOS BICHOS QUE HAYAN PARTICIPADO EN 2 O MAS COMBATES
SELECT B.ID,B.Nombre,COUNT(UBC.[ID-Bicho]) [CANTIDAD]FROM BICHO B INNER JOIN [USUARIO-BICHO-COMBATE] UBC
ON B.ID=UBC.[ID-Bicho]
group by B.ID,B.Nombre
HAVING count(UBC.[ID-Bicho]) >= 2
--CONSULTA 9 MOSTRAR EL ID DEL USUARIO QUE HAYA GANADO EL UNICO COMBATE DONDE COMBATIO
SELECT U.ID from USUARIO U INNER JOIN COMBATE C
ON U.ID=C.[Id-Usuario] OR U.ID=C.[Id-Usuario2] 
GROUP BY U.ID
HAVING COUNT(C.[Id-Usuario])=1
INTERSECT 
SELECT C.Ganador FROM COMBATE C

--CONSULTA 10 MOSTRAR EL ATAQUE QUE UTILIZO EL BICHO1 EN X RONDA, QUE DAÑO CAUSO Y SU PROPIETARIO
SELECT B.Propietario,B.ID, R.NúmeroRonda, B.Nombre[BICHO],A.Descripción[ATAQUE],A.Daño FROM RONDA R INNER JOIN [RONDA-ATAQUE-BICHO] RAB ON R.ID=RAB.[ID-Ronda]
INNER JOIN BICHO B ON B.ID = R.[Id-BichoUsuario1]
INNER JOIN ATAQUE A ON A.ID=RAB.[ID-AtaqueBicho1]
WHERE R.ID = 1
--CONSULTA 11 MOSTRAR AQUELLOS BICHOS CUYO ATAQUE SOLAMENTE SEA " "
SELECT B.ID FROM BICHO B INNER JOIN [BICHO-ATAQUE] BA ON B.ID=BA.[ID-Bicho]
INNER JOIN ATAQUE A ON A.ID=BA.[ID-Ataque]
EXCEPT
SELECT BA.[ID-Bicho] FROM [BICHO-ATAQUE] BA INNER JOIN ATAQUE A ON  BA.[ID-Ataque]=A.ID
WHERE A.Descripción NOT LIKE 'FOCO RESPLANDOR'
--CONSULTA 12 MOSTRAR AQUELLOS TIPOS QUE NO TENGAN DEBILIDAD ANTE OTROS TIPOS
SELECT T.ID FROM  TIPOBICHO T 
EXCEPT 
SELECT T.[Id-Tipo] FROM [TIPO-DEBILIDAD] T

--CONSULTA 13 MOSTRAR AQUELLOS TIPOS QUE SOLAMENTE TENGAN DEBILIDAD ANTE TIPO X
SELECT T.ID FROM  TIPOBICHO T 
EXCEPT 
SELECT T.[Id-Tipo] FROM [TIPO-DEBILIDAD] T
WHERE NOT T.[Id-Tipo-Debilidad]=1
	
--CONSULTA 14 MOSTRAR AQUELLOS TIPOS QUE SOLAMENTE TENGAN 2 O MAS DEBILIDADES ANTE OTROS TIPOS
SELECT T.ID,COUNT(TD.[Id-Tipo-Debilidad]) AS CANTIDAD FROM  TIPOBICHO T INNER JOIN [TIPO-DEBILIDAD] TD
ON T.ID=TD.[Id-Tipo]
group by T.ID
HAVING COUNT(TD.[Id-Tipo-Debilidad]) >=2
--CONSULTA 15 CUANTOS BICHOS CAPTURARON LOS USUARIOS DURANTE UN LAPSO DE TIEMPO
SELECT U.UserName,COUNT(UCB.[Id-Usuario]) [BICHOS CAPTURADOS] FROM [USUARIO-CAPTURA-BICHO] UCB 
INNER JOIN USUARIO U ON U.ID=UCB.[Id-Usuario]
WHERE  UCB.fecha BETWEEN '20170101' AND '20170808'
GROUP BY U.UserName

--CONSULTA 16 MOSTRAR AQUELLOS USUARIOS QUE NO HAYAN CAPTURADO Y QUE SEA PROPIETARIO DE 0 BICHOS 
SELECT ID FROM USUARIO
EXCEPT 
SELECT [Id-Usuario] FROM [USUARIO-CAPTURA-BICHO]
EXCEPT 
SELECT Propietario FROM BICHO

--CONSULTA 17 MOSTRAR AQUELLOS TIPOS QUE NO TENGAN FORTALEZA ANTE OTROS TIPOS
SELECT * FROM [TIPO-FORTALEZA] 
SELECT T.ID FROM TIPOBICHO T
EXCEPT
SELECT T.[Id-Tipo] FROM [TIPO-FORTALEZA] T

--CONSULTA 18 MOSTRAR LA UBICACIÓN DONDE HAN SIDO CAPTURADOS MAYOR DE 5 BICHOS
SELECT UCB.[Id-Ubicación],U.Descripción, COUNT(UCB.[Id-Ubicación]) AS [BICHOS CAPTURADOS] FROM [USUARIO-CAPTURA-BICHO] UCB
INNER JOIN UBICACIÓN U ON U.Id=UCB.[Id-Ubicación]
GROUP BY UCB.[Id-Ubicación],U.Descripción
HAVING COUNT(UCB.[Id-Ubicación])>5


--CONSULTA 19 MOSTRAR LOS USUARIOS HAYAN PARTICIPADO EN AL MENOS UN COMBATE PERO NO HAYAN GANADO COMBATES
SELECT U.ID FROM USUARIO U INNER JOIN COMBATE C
ON U.ID=C.[Id-Usuario] OR U.ID=C.[Id-Usuario]
GROUP BY U.ID
HAVING COUNT(C.[Id-Usuario])>=1
EXCEPT 
SELECT C.Ganador FROM COMBATE C
--CONSULTA 20 MOSTRAR LOS USUARIOS QUE NO HAN PARTICIPADO EN UN INTERCAMBIO PERO SI UN COMBATE
SELECT U.ID FROM USUARIO U 
EXCEPT 
SELECT I.[Id-Usuario1] FROM INTERCAMBIO I
EXCEPT 
SELECT I.[Id-Usuario2] FROM INTERCAMBIO I
INTERSECT
SELECT C.[Id-Usuario] FROM COMBATE C
INTERSECT
SELECT C.[Id-Usuario2] FROM COMBATE C

--CONSULTAS TRIVIALES

--CONSULTA 1 MOSTRAR LA ESPECIE MAS VELOZ, SU NOMBRE, ID
SELECT E.ID,E.Nombre FROM ESPECIE E 
WHERE E.Velocidad=(SELECT MAX(E.Velocidad) FROM ESPECIE E)
--CONSULTA 2 MOSTRAR AQUELLAS ESPECIES QUE TENGAN 2 0 MÁS EVOLUCIONES
SELECT E.ID  FROM ESPECIE E INNER JOIN EVOLUCION EV 
ON E.ID=EV.[ID-Especie]
GROUP BY E.ID 
HAVING COUNT(EV.[ID-Especie])>=2
--CONSULTA 3 MOSTAR CANTIDAD DE ESPECIES, POR TIPO
SELECT T.ID,T.Descripción,COUNT(E.Tipo)AS [CANTIDAD DE ESPECIES] FROM TIPOBICHO T INNER JOIN ESPECIE E
ON T.ID=E.Tipo
GROUP BY T.ID,T.Descripción
--CONSULTA 4 CUANTOS BICHOS CONTIENE CADA USUARIO
SELECT U.ID,U.UserName, COUNT(B.Propietario) AS [CANTIDAD DE BICHOS] FROM USUARIO U INNER JOIN BICHO B
ON U.ID=B.Propietario
GROUP BY U.ID,U.UserName
--CONSULTA 5 MOSTRAR EL BICHO, EL NOMBRE DEL ATAQUE, Y AL TIPO QUE AMBOS PERTENECEN
SELECT B.Id,B.Nombre,A.Descripción,T.Descripción FROM BICHO B INNER JOIN [BICHO-ATAQUE] BA ON B.ID=BA.[ID-Bicho]
 INNER JOIN ATAQUE A ON A.ID=BA.[ID-Ataque] 
 INNER JOIN TIPOBICHO T ON A.Tipo=T.ID
--CONSULTA 6 MOSTRAR EL NOMBRE DEL BICHO Y A QUIEN LE PERTENECE
SELECT B.ID AS [IdBicho],B.Nombre AS [NOMBRE DEL BICHO],U.UserName FROM BICHO B INNER JOIN USUARIO U
ON U.ID=B.Propietario
--CONSULTA 7 MOSTRAR EL PROMEDIO DE SALUD DE TODAS LAS ESPECIES
SELECT AVG(E.SaludMax) AS PROMEDIO FROM ESPECIE E
--CONSULTA 8 MOSTRAR EL PROMEDIO DE VELOCIDAD DE TODAS LAS ESPECIES
SELECT AVG(E.Velocidad) AS PROMEDIO FROM ESPECIE E
--CONSULTA 9 MOSTRAR EL PROMEDIO DE EXPERIENCIA DE TODAS LOS BICHOS
SELECT AVG(B.Experiencia) AS PROMEDIO FROM BICHO B
--CONSULTA 10 MOSTRAR LA ESPECIE CS+NON MAYOR SALUD, SU NOMBRE, ID
SELECT E.ID,E.Nombre,E.SaludMax FROM ESPECIE E 
WHERE E.SaludMax=(SELECT MAX(E.SaludMax) FROM ESPECIE E)
--CONSULTA 11 MOSTRAR EL BICHO CUYA SU EXPERENCIA SEA LA MAYOR
SELECT B.ID,B.Nombre,B.Experiencia FROM BICHO B
WHERE B.Experiencia=(SELECT MAX(B.Experiencia) FROM BICHO B)
--CONSULTA 12 MOSTRAR CUANTOS BICHOS TIENE CADA ESPECIE
SELECT E.ID,E.Nombre,COUNT(B.Especie) AS [CANTIDAD DE BICHOS]FROM BICHO B INNER JOIN ESPECIE E
ON B.Especie=E.ID
GROUP BY E.ID,E.Nombre
--CONSULTA 13 MOSTRAR CUANTAS ESPECIES PERTENECEN A LOS TIPOS
SELECT T.ID,T.Descripción,COUNT(E.Tipo) AS [CANTIDAD DE ESPECIES] FROM ESPECIE E INNER JOIN TIPOBICHO T
ON E.Tipo=T.ID
GROUP BY T.ID,T.Descripción
--CONSULTA 14 MOSTRAR LOS COMBATES Y SUS GANADORES
SELECT C.ID,U.UserName AS GANADOR FROM COMBATE C INNER JOIN USUARIO U
ON U.ID=C.Ganador
--CONSULTA 15 MOSTRAR TODOS LOS COMBATES Y SUS RONDAS CORRESPONDIENTES
SELECT C.ID as IdCombate,C.Fecha,R.ID AS IdRonda,R.NúmeroRonda FROM COMBATE C INNER JOIN RONDA R
ON C.ID=R.[Id-Combate]
--CONSULTA 16 MOSTRAR TODOS LOS COMBATES DONDE X BICHO PARTICIPO
SELECT B.ID,UBC.[ID-Combate],C.Fecha FROM BICHO B INNER JOIN [USUARIO-BICHO-COMBATE] UBC
ON B.ID=UBC.[ID-Bicho] INNER JOIN COMBATE C ON C.ID=UBC.[ID-Combate]
WHERE B.ID=10
--CONSULTA 17 MOSTRAR TODOS LOS COMBATES DONDE X USUARIO GANÓ
SELECT U.ID,C.Fecha FROM USUARIO U INNER JOIN COMBATE C ON U.ID=C.[Ganador]
WHERE U.ID=3
--CONSULTA 18 MOSTRAR TODOS LOS BICHOS QUE HAN SIDO UTILIZADO EN COMBATES
SELECT B.ID,B.Nombre,C.ID AS COMBATE FROM BICHO B INNER JOIN [USUARIO-BICHO-COMBATE] UBC ON B.ID=UBC.[ID-Bicho] 
INNER JOIN COMBATE C ON C.ID=UBC.[ID-Combate]
--CONSULTA 19 MOSTRAR TODOS LOS ATAQUES QUE UTILIZO X BICHO EN SUS COMBATES
SELECT B.ID,B.Nombre,C.ID AS COMBATE,R.ID AS Ronda,R.NúmeroRonda,A.Descripción,A.Daño FROM BICHO B INNER JOIN [USUARIO-BICHO-COMBATE] UBC ON B.ID=UBC.[ID-Bicho] 
INNER JOIN COMBATE C ON C.ID=UBC.[ID-Combate]
INNER JOIN RONDA R ON R.[Id-Combate]=C.ID 
INNER JOIN [RONDA-ATAQUE-BICHO] RAB ON RAB.[ID-Ronda]=R.ID
INNER JOIN ATAQUE A ON A.ID=RAB.[ID-AtaqueBicho1]
WHERE B.ID=1
--CONSULTA 20 MOSTRAR AQUELLOS BICHOS QUE HAYAN SIDO INTERCAMBIADOS Y SU ACTUAL PROPIETARIO
SELECT B.ID,U.UserName AS PropietarioActual FROM BICHO B INNER JOIN INTERCAMBIO I ON B.ID=I.[Id-Bicho1] OR B.ID=I.[Id-Bicho2]
INNER JOIN USUARIO U ON U.ID=B.Propietario
--CONSULTA 21 MOSTRAR LA CANTIDAD DE BICHOS QUE CADA USUARIO A INTERCAMBIADO
SELECT U.ID,U.UserName,COUNT(I.[Id-Usuario1]) AS [BICHOS INTERCAMBIADOS] FROM USUARIO U INNER JOIN INTERCAMBIO I 
ON U.ID=I.[Id-Usuario1] 
GROUP BY U.ID,U.UserName
--CONSULTA 22 MOSTRAR CUANTAS VECES HA SIDO INTERCAMBIADO UN BICHO
SELECT B.ID,B.Nombre,COUNT(I.[Id-Usuario1]) AS [BICHOS INTERCAMBIADOS] FROM BICHO B INNER JOIN INTERCAMBIO I 
ON B.ID=I.[Id-Bicho1] OR B.ID=I.[Id-Bicho2]
GROUP BY B.ID,B.Nombre
--CONSULTA 23 MOSTRAR CUANTOS BICHOS HAN SIDO CAPTURADOS EN UN CADA UBICACIÓN
SELECT U.Id as IdUbicación,U.Descripción,COUNT(UCB.[Id-Ubicación]) AS Cantidad FROM [USUARIO-CAPTURA-BICHO] UCB 
INNER JOIN UBICACIÓN U ON U.Id=UCB.[Id-Ubicación]
GROUP BY U.Id,U.Descripción
--CONSULTA 24 MOSTAR LAS DEBILIDADES DE LAS ESPECIES
SELECT E.ID,E.Nombre,T.Descripción AS TIPO,T2.Descripción AS Debilidad  FROM ESPECIE E INNER JOIN TIPOBICHO T ON E.Tipo=T.ID 
INNER JOIN [TIPO-DEBILIDAD] TD ON TD.[Id-Tipo]=T.ID
INNER JOIN TIPOBICHO T2 ON T2.ID=TD.[Id-Tipo-Debilidad]
--CONSULTA 25 MOSTAR LAS FORTALEZAS DE LAS ESPECIES
SELECT E.ID,E.Nombre,T.Descripción AS TIPO,T2.Descripción AS Fortaleza  FROM ESPECIE E INNER JOIN TIPOBICHO T ON E.Tipo=T.ID 
INNER JOIN [TIPO-FORTALEZA] TF ON TF.[Id-Tipo]=T.ID
INNER JOIN TIPOBICHO T2 ON T2.ID=TF.[Id-Tipo-Fortaleza]
--CONSULTA 26 MOSTRAR LAS EVOLUCIONES DE CADA ESPECIE
SELECT E.ID,E.Nombre,E2.Nombre AS Evolución FROM ESPECIE E INNER JOIN EVOLUCION EV ON E.ID=EV.[ID-Especie]
INNER JOIN ESPECIE E2 ON E2.ID=EV.Evolución
--CONSULTA 27 MOSTRAR EL PROMEDIO DE EXPERIENCIA NECESARIA PARA UNA EVOLUCIÓN
SELECT AVG(E.ExperenciaNecesaria) AS PromedioDeExperencia  FROM EVOLUCION E 
--CONSULTA 28 MOSTRAR AQUELLOS ATAQUES QUE PUEDEN APRENDER LAS ESPECIES
SELECT E.ID AS IdEspecie,E.Nombre,A.Descripción AS [ATAQUE POR APRENDER],A.Daño FROM ESPECIE E INNER JOIN [ATAQUE-POR-APRENDER] APA ON APA.[Id-Especie]=E.ID
INNER JOIN ATAQUE A ON APA.[Id-Ataque]=A.ID
--CONSULTA 29 EN CUANTOS BICHOS HAN SIDO CAPTURADOS POR TODOS LOS USUARIOS EN UN LAPSO DE TIEMPO
SELECT COUNT(UCB.[Id-Bicho])  AS BichosCapturados FROM [USUARIO-CAPTURA-BICHO] UCB 
WHERE UCB.Fecha BETWEEN '20170101' AND '20170808'
--CONSULTA 30 MOSTRAR CANTIDAD DE ATAQUES QUE UN BICHO PUEDE HACER
SELECT B.ID,B.Nombre,COUNT(BA.[ID-Bicho]) AS CantidadAtaques FROM BICHO B INNER JOIN [BICHO-ATAQUE] BA ON BA.[ID-Bicho]=B.ID
GROUP BY  B.ID,B.Nombre



--VISTAS--
CREATE VIEW VISTABICHOS
AS
SELECT ID,NOMBRE
FROM BICHO

select * from  VISTABICHOS

CREATE VIEW [VISTA-ATAQUES-BICHOS]
AS
SELECT BA.[ID-Bicho],Ba.[Id-Ataque]
FROM [BICHO-ATAQUE] BA

CREATE VIEW [VISTA-ATAQUE]
AS
SELECT ID,DESCRIPCION
FROM [ATAQUE] A

select * from [VISTA-ATAQUES-BICHOS]
select * from [VISTA-ATAQUE]
select VB.NOMBRE,VAB.[Id-Ataque] from VISTABICHOS VB
INNER JOIN [VISTA-ATAQUES-BICHOS] VAB ON VAB.[ID-Bicho]=VB.ID
INNER JOIN [VISTA-ATAQUE] VA ON VA.ID=VAB.[Id-Ataque]
where VB.ID=1