--CONSULTAS--

--CONSULTAS NO TRIIVIALES

--CONSULTA 1 MOSTRAR EL PROMEDIO DE ATAQUE DE BICHO POR TIPO

--CONSULTA 2 MOSTRAR EL PROMEDIO DE SALUD POR TIPO

--CONSULTA 3 MOSTRAR EL BICHO MAS VELOS, SU NOMBRE, ID, Y SU TIPO

--CONSULTA 4 MOSTRAR AQUELLOS BICHOS QUE NO TENGAN EVOLUCIÓN

--CONSULTA 5 MOSTRAR AQUELLOS BICHOS QUE TENGAN 2 0 MÁS EVOLUCIONES

--CONSULTA 6 MOSTRAR AQUELLOS BICHOS QUE HAN SIDO INTERCAMBIADOS

--CONSULTA 7 MOSTRAR AQUELLOS BICHOS QUE NO HAYAN PARTICIPADO EN UN COMBATE

--CONSULTA 8 MOSTRAR AQUELLOS BICHOS QUE HAYAN PARTICIPADO EN 2 O MAS COMBATES

--CONSULTA 9 CUANTOS BICHOS CONTIENE CADA USUARIO

--CONSULTA 10 MOSTAR CANTIDAD DE BICHOS, SU ID, Y SUS ATAQUES POR TIPO

--CONSULTA 11 MOSTRAR AQUELLOS BICHOS CUYO ATAQUE SOLAMENTE SEA " "

--CONSULTA 12 MOSTRAR AQUELLOS TIPOS QUE NO TENGAN DEBILIDAD ANTE OTROS TIPOS

--CONSULTA 13 MOSTRAR AQUELLOS TIPOS QUE SOLAMENTE TENGAN DEBILIDAD ANTE OTROS TIPOS

--CONSULTA 14 MOSTRAR AQUELLOS TIPOS QUE SOLAMENTE TENGAN 2 O MAS DEBILIDADES ANTE OTROS TIPOS

--CONSULTA 15 CUANTOS BICHOS CAPTURO EL USUARIO X DURANTE UN LAPSO DE TIEMPO

--CONSULTA 16 MOSTRAR AQUELLOS USUARIOS QUE NO HAYAN CAPTURADO Y QUE SEA PROPIETARIO DE 0 BICHOS 

--CONSULTA 17 MOSTRAR AQUELLOS TIPOS QUE NO TENGAN FORTALEZA ANTE OTROS TIPOS

--CONSULTA 18 MOSTRAR LOS USUARIOS Y LOS BICHOS QUE FUERON CAPTURADOS EN LA MISMA UBICACION

--CONSULTA 19 MOSTRAR LOS USUARIOS QUE NO HAN PARTICIPADO EN UN COMBATE

--CONSULTA 20 MOSTRAR LOS USUARIOS QUE NO HAN PARTICIPADO EN UN INTERCAMBIO

--CONSULTA 21 MOSTRAR LOS BICHOS QUE HAYAN PARTICIPADO EN COMBATES, PERO NO EN UNA RONDAS
 
--CONSULTA 22 MOSTRAR LOS BICHOS QUE HAYAN PARTICIPADO EN COMBATES, PERO SOLAMENTE EN UNA RONDA
